### PR TITLE
[WIP] improving documentation

### PR DESCRIPTION
**Pull request by aretecode**

### CODE REVIEW

**Comment by bergie** [comment]
I think this PR needs to be cleaned and made again. It says "175 files changed" which is definitely outside the scope of just documentation updates

**Comment by jonnor** [comment]
@aretecode there are hundreds of files changed due to some permissions / file mode changes. This is (very likely) completely uneccesary and makes it very hard to review the PR. Please fix.

It can for instance by making a new branch, picking the desired changes, and opening a new PR.

**Comment by trustmaster** [comment]
Now that `0.8.0` is out, something needs to be done about this PR for @aretecode's work not to be lost.

**Comment by bergie** [comment]
Cleaned up and updated version of this PR in #64

**Pull request closed without merging**
